# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79c00f8a013372c37d588919dff4cc1974326009c6fc719263ed6ef17f2d3793ac6e1fe4b18b6fd01df5ca391a8cc11d3368829319889dcf77ef8017ac56b6f

test:
  secret_key_base: 3ff00b2ea7c4d4c54dc364cb4eebfe987b72a9b7eb8735e95e9e606264ab2a0cb5d8cb80fc7192f749c689ab91d2e5b8ab4bad7d788691288ef6dd884ffca83b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
